# Generated by Django 3.2.3 on 2021-05-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_min',
            new_name='image_main',
        ),
    ]
